[workspace]
pcb-version = "0.4"
vendor = ["code.diode.computer/diode/registry/**"]

[board]
name = "dwm1004c_aptwr_tag"
path = "dwm1004c_aptwr_tag.zen"
description = "Replace with concise board description."

[access]
allow = ["*"]